### ISSUE TITLE
Should handle terminating namespace more gracefully

### ISSUE THREAD

**Issue by erikgb** [nais/azurerator#20]
Occasionally azurerator attempts to operate on resources in terminating namespaces. This results in errors being logged (see below for an example). IMO errors like this should be ignored by the operator to avoid polluting logs.

````json
{
   "CorrelationID":"022865c0-a590-48d3-9f28-1c0aa2ffc0de",
   "application_name":"sf6-adapter-frontend",
   "application_namespace":"sf6-adapter-renovate-major",
   "level":"error",
   "msg":"failed to process AzureAdApplication: processing secrets: creating or updating secret sf6-adapter-frontend-azure: secrets \"sf6-adapter-frontend-azure\" is forbidden: unable to create new content in namespace sf6-adapter-renovate-major because it is being terminated",
   "time":"2022-12-21T15:55:58.356110399Z"
}
````

We filter out this type of error from logs from in-house operators by regex-matching the error message. Please let me know if you need code examples.

**Comment by tronghn** [comment]
Seems reasonable. I guess the controller-runtime informer doesn't know or ignore events related to namespace termination? 

Not really a fan of regex-matching error messages, but how about something like this:

```go
if apierrors.HasStatusCause(err, corev1.NamespaceTerminatingCause) {
	// do not requeue reconciliation as all subsequent attempts will fail
	return ctrl.Result{}, nil
}
```

**Comment by erikgb** [comment]
Sounds good to me! I just tried this out with one of our in-house operators, and it works. The only downside is the complex code to test this, ref. how it is done in Kubernetes: https://github.com/kubernetes/kubernetes/blob/9918aa1e035a00bc7c0f16a05e1b222650b3eabc/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go#L169-L183

**Comment by tronghn** [comment]
Yeah, it's fairly convoluted. Though, one could argue that the tests covered by these modules would cover most of the implementation details (ref. https://github.com/kubernetes/kubernetes/blob/00aae4c10c204d258e62a96f30970e9b91b29149/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission_test.go#L181-L231 and https://github.com/kubernetes/kubernetes/blob/00aae4c10c204d258e62a96f30970e9b91b29149/staging/src/k8s.io/apimachinery/pkg/api/errors/errors_test.go#L629-L659).

I'm gonna go ahead and apply the suggested fix for now. Thanks for opening the issue 🙂
